### ISSUE TITLE
Basic user documentation

### ISSUE THREAD

**Issue by haesleinhuepf** [hanjinliu/napari-spreadsheet#1]
Hi @hanjinliu ,

this plugin is super amazing! Do you have some basic user documentation that could be linked from then [napari-hub page](https://www.napari-hub.org/plugins/napari-spreadsheet) and github readme?

Thanks!

Best,
Robert

**Comment by hanjinliu** [comment]
Hi @haesleinhuepf ,
thank you for the suggestion! There are some documentations in the `tabulous` page but yes, it's a great idea to have a link here as well.
